# Generated by Django 5.2.1 on 2025-06-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[("STUDENT", "Student"), ("LIBRARIAN", "Librarian")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
